services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./output:/output
    ports:
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
      - AGENCY_QUORUM_MIN=1
      - SERVER_HOST=server
      - SERVER_PORT=5678

  client_0:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_0
    depends_on:
      - server
    volumes:
      - ./input:/input
      - ./output:/output
    environment:
      - AGENCY_ID=0
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - BATCH_SIZE=3
      - INPUT_FILE=/input/input-0.csv
      - OUTPUT_FILE=/output/winers.txt

  client_2:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_2
    depends_on:
      - server
    volumes:
      - ./input:/input
    environment:
      - AGENCY_ID=2
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - BATCH_SIZE=3
      - INPUT_FILE=input/input-0.csv
      - OUTPUT_FILE=output/winers.txt
